---
title: "Temp2"
output: NA
---


```{r setup}
library(magrittr)
library(lubridate)
```

```{r}
cont <- 
  contract() %>% 
  term_start(
    as.Date("2000/01/01"), 
    id = "Purchase date",
    payment = 1000,
    receipt = 50,
    consideration = 0.06 * par_vale()
    )

View(cont)

```


```{r}
is.list(contract())
```


```{r}
contract_a <-
  contract() %>%
  term_start(dmy("01/01/2018")) 

class(contract_a[["terms"]][[1]])
```

```{r}
events <- 
    contract() %>%
    term_start(dmy("01/01/2018"), event_name = "purchase date") %>%
    schedule()

val <- events[1, "event_type"] %>% dplyr::pull()

val == "purchase date"
```
```{r}
events <-
    contract() %>%
    term_start(dmy("01/01/2018"), receipt = 100) #%>%
    #schedule()

  #expect_equal(events[1, "event_type"] %>% dplyr::pull(),"purchase date")
as.numeric(events$stipulations[[2]])
```

```{r}
contract_a <-
  contract() %>%
  term_start(as.Date("2000/02/01"), receipt = 1000) #%>% 
  #schedule()

as.numeric(contract_a$stipulations[[2]]) == 1000
```

```{r}
contract_a <- 
  contract() %>% 
  term_start(dmy("01/01/2018"), receipt = 1000) #%>% 
  #schedule()

contract_a
```


```{r}
a_contract <-
  contract() %>% 
  term_start(dmy("01/01/2000"), payment =  1000, event_name = "purchase date") %>% 
  term_end(dmy("31/12/2000"), receipt =  1000, event_name = "sale date") 
  
  

events <-
  a_contract %>% 
  schedule()

#events[1,2] %>% dplyr::pull()

events
```


```{r}
make_date_seq(dmy("31/01/2000"), dmy("31/12/2000"), months(1))
```

```{r}
seq.Date(from = dmy("01/01/2000"), to = dmy("15/02/2000"), by = "month")
```

```{r}
make_date_seq(
  dmy("31/01/2000"),
  dmy("31/12/2000"), 
  "qUarterly",
  tolerance = 0.8,
  include_first = T,
  include_last = T,
  replace_last = F,
  allow_last_jump = T)
```

```{r}
contract_a <- 
  contract() %>% 
  term_start(dmy("01/01/2000"), payment = 1000) %>% 
  term_end(dmy("01/12/2000"), receipt = 1000) %>% 
  term_series(freq = months(1), 
              from = dmy("01/01/2000"), 
              to = dmy("01/12/2000"), 
              amount = 100,
              include_first = F,
              include_last = F) 

#View(contract_a)
contract_a %>% schedule()
```

